
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_device
      MYSQL_USER: device_user
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306' 
    volumes:
      - mysql_data:/var/lib/mysql

  authdevice:
    build: .
    container_name: auth_device_service
    ports:
      - '3004:3004'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: device_user
      DB_PASSWORD: root
      DB_NAME: db_device
      JWT_SECRET: supersecreto123
      RISK_ANALYSIS_URL: http://192.168.1.6:3006/risk

volumes:
  mysql_data:
