version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
      MYSQL_USER: authuser
      MYSQL_PASSWORD: authuserpass
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  authuser:
    build: .
    ports:
      - '3002:3002'
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: authuser
      DB_PASSWORD: authuserpass
      DB_NAME: auth_db
      JWT_SECRET: supersecreto123
      RISK_ANALYSIS_URL: http://riskanalysis:3006/risk

volumes:
  mysql_data:
