version: '3.8'

services:
  accessproxy:
    build: .
    container_name: access_proxy_service
    ports:
      - '3003:3003'
    environment:
      ACCESS_CONTROL_URL: http://accesscontrol:3005/graphql

