version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: risk_container
    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: riskDB
      MYSQL_USER: risk_user
      MYSQL_PASSWORD: root
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: